from app import *
class MainUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(AVAILABLE_WIDTH, AVAILABLE_HEIGHT)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, AVAILABLE_WIDTH, AVAILABLE_HEIGHT // 32))
        self.menubar.setObjectName("menubar")
        self.menuLive_Streaming = QMenu(self.menubar)
        self.menuLive_Streaming.setObjectName("menuLive_Streaming")
        self.menuLive_Streaming_FPS_BW = QMenu(self.menuLive_Streaming)
        self.menuLive_Streaming_FPS_BW.setObjectName("menuLive_Streaming_FPS_BW")
        self.menuLive_Histogram_Contrast = QMenu(self.menuLive_Streaming)
        self.menuLive_Histogram_Contrast.setObjectName("menuLive_Histogram_Contrast")
        self.menuAdditional_Features = QMenu(self.menubar)
        self.menuAdditional_Features.setObjectName("menuAdditional_Features")
        self.menuI_and_P_Frames_WDR = QMenu(self.menuAdditional_Features)
        self.menuI_and_P_Frames_WDR.setObjectName("menuI_and_P_Frames_WDR")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_1_Stream = QAction(MainWindow)
        self.action_1_Stream.setObjectName("action_1_Stream")
        self.action_2_Streams = QAction(MainWindow)
        self.action_2_Streams.setObjectName("action_2_Streams")
        self.action_3_Streams = QAction(MainWindow)
        self.action_3_Streams.setObjectName("action_3_Streams")
        self.action_Histogram_Contrast = QAction(MainWindow)
        self.action_Histogram_Contrast.setObjectName("actionGray_Scale_Histogram_Contrast")
        self.actionDead_Pixels_Detector = QAction(MainWindow)
        self.actionDead_Pixels_Detector.setObjectName("actionDead_Pixels_Detector")
        self.actionAttach_a_Video = QAction(MainWindow)
        self.actionAttach_a_Video.setObjectName("actionAttach_a_Video")
        self.menuLive_Streaming_FPS_BW.addAction(self.action_1_Stream)
        self.menuLive_Streaming_FPS_BW.addSeparator()
        self.menuLive_Streaming_FPS_BW.addAction(self.action_2_Streams)
        self.menuLive_Streaming_FPS_BW.addSeparator()
        self.menuLive_Streaming_FPS_BW.addAction(self.action_3_Streams)
        self.menuLive_Histogram_Contrast.addAction(self.action_Histogram_Contrast)
        self.menuLive_Histogram_Contrast.addSeparator()
        self.menuLive_Streaming.addAction(self.menuLive_Streaming_FPS_BW.menuAction())
        self.menuLive_Streaming.addSeparator()
        self.menuLive_Streaming.addAction(self.menuLive_Histogram_Contrast.menuAction())
        self.menuLive_Streaming.addSeparator()
        self.menuLive_Streaming.addAction(self.actionDead_Pixels_Detector)
        self.menuI_and_P_Frames_WDR.addAction(self.actionAttach_a_Video)
        self.menuAdditional_Features.addAction(self.menuI_and_P_Frames_WDR.menuAction())
        self.menubar.addAction(self.menuLive_Streaming.menuAction())
        self.menubar.addAction(self.menuAdditional_Features.menuAction())
        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", APP_NAME))
        self.menuLive_Streaming.setTitle(_translate("MainWindow", "Live Streaming"))
        self.menuLive_Streaming_FPS_BW.setTitle(_translate("MainWindow", "Live Streaming, FPS, BW"))
        self.menuLive_Histogram_Contrast.setTitle(_translate("MainWindow", "Live Histogram, Contrast"))
        self.menuAdditional_Features.setTitle(_translate("MainWindow", "Additional Features"))
        self.menuI_and_P_Frames_WDR.setTitle(_translate("MainWindow", "I and P Frames, WDR"))
        self.action_1_Stream.setText(_translate("MainWindow", "1 x (25 FPS, 1920x1080) Stream"))
        self.action_2_Streams.setText(_translate("MainWindow", "2 x (12 FPS) Streams"))
        self.action_3_Streams.setText(_translate("MainWindow", "3 x (8 FPS) Streams"))
        self.action_Histogram_Contrast.setText(_translate("MainWindow", "Histogram, Contrast"))
        self.actionDead_Pixels_Detector.setText(_translate("MainWindow", "Dead Pixels Detector"))
        self.actionAttach_a_Video.setText(_translate("MainWindow", "Attach a Video"))